name = "Plane Turbulence";
dir = "@Plane_Turbulence";
author = "Seb";
actionName = "Website";
action = "http://www.carpenoctem.co";
description = "Github: https://github.com/Seb105/Arma-Plane-Turbulence";
tooltip = "Plane Turbulence";
tooltipOwned = "Plane Turbulence Owned";
overview = "Adds dynamic turbulence to planes based on their size, mass and the weather!";
overviewText = "Plane Turbulence Overview";
logoSmall	 = "logoSmall.paa";	// Display next to the item added by the mod
logo		 = "logo.paa";			// Logo displayed in the main menu
logoOver	 = "logoOver.paa";	